#!/bin/bash

ANDROID_BUILD_TOP="$(dirname $(realpath "$0"))"
[[ "${ANDROID_BUILD_TOP##*/}" == "lineageos-rootdir" ]] && ANDROID_BUILD_TOP="$(dirname "$ANDROID_BUILD_TOP")"
CHECK="$(echo $1 | grep -q check && echo 1)"
GERRIT_USERNAME="rofikkernel"

function repopick() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "${@: -1} - " ; ssh lineage-gerrit gerrit query ${@: -1} --format=JSON | jq --slurp -r '.[0].status'
    else
        ${ANDROID_BUILD_TOP}/vendor/lineage/build/tools/repopick.py \
            -g "ssh://$GERRIT_USERNAME@review.lineageos.org:29418" $@ &
    fi
}

function repopickchain() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "$1 - " ; ssh lineage-gerrit gerrit query $1 --format=JSON | jq --slurp -r '.[0].status'
    else
        `${croot}/gen_chain $@`
    fi
}

function rc() {
    echo `${ANDROID_BUILD_TOP}/gen_chain $@ | cut -b10-`
}

#
# _examples_
#
# # repo/1
# changes=(
#     2137 # hello
#     `rc 2137` # hello (chain)
# )
# repopick ${changes[@]}
#
# # repo/2
# repopick -p 2137 # hello (chain)
#
# # repo/3
# repopick 2137 # hello
#

# build/make
repopick 433127 # -latest

#android
repopick -p 436442 # -latest

# bionic
repopick -p 433204 # Add ability to build scudo-free 32-bit libc variant.

# bootable/deprecated-ota
repopick -p 433207 # updater: Support loading dynamic partition metadata from OTA

# bootable/recovery
repopick -p 437117 # minui: latest

# build/make
repopick -p 433127 #latest

# build/soong 
#repopick -p 433201 #Support prebuilt_kernel_headers
repopick -p 433187 #latest lAdd ability to enable scudo-free 32-bit libc variant.

# external/arm-trusted-firmware
#repopick -p 433317 #merge Partial Revert "Tegra: memctrl: cleanup streamid override registers"

# external/avb
#repopick -p 433319 #merge avbtool: Add retry to generate_fec_data()

# device/google/contexthub
repopick 433315 #latest  contexthub: sensorhal: allow building it again with Android.bp

# device/generic/goldfish
repopick -p 435541 #latest goldfish: Remove NavigationBarMode2ButtonOverlay

# device/google/atv
repopick -p 433314 # products: Make generic x86_64 TV target inherit 64bit_only

# external/cronet
repopick 433320 # cronet: Fix build with custom out directory

# external/dtc
#repopick -p 433334 #merge Add build support for more host utils

# external/e2fsprogs
repopick -p 433337 #latest e2fsck: Loosen fscrypt_policy struct size check

# external/gptfdisk
repopick -p 433344 # latest gptfdisk: Make libgptf available to product/vendor

# external/mksh
#repopick -p 433347 # merged mksh: Set TERM to xterm-256color

# external/nano
#repopick -p 435356 #merge nano: Regenerate config.h

# external/setupcompat
repopick -p 433354 # latest Change some more defaults

# external/tinycompress
#repopick -p 433356 #merged tinycompress: Add conditional compilation check for compress param

# external/wpa_supplicant_8
#repopick 433358 #merge wpa_supplicant: add support for bcmdhd SAE authentication offload

# external/zstd
#repopick -p 433360 #merge zstd: Android.bp: Allow rsync to add zstd compression support

# frameworks/av
repopick -p 437109 # latest

# frameworks/base
repopick -p 437656 # latest

# frameworks/native
repopick -p 433383 # latest

# frameworks/opt/calendar
#repopick 433385 #abandoned fix invalid time being set when `Time.set(Time)` is being called on itself

# frameworks/opt/colorpicker
#repopick 433386 #abandon Migrate to androidx

# frameworks/opt/telephony
repopick -p 433395 #latest telephony: Make "Do not ask again" functional

# frameworks/opt/timezonepicker
#repopick -p 433398 #abandoned Migrate to androidx fragment library

# hardware/broadcom/libbt
repopick -p 433406 #latest Improve UART baud rate handling

# hardware/google/pixel
repopick -p 433415 #latest pixel: Disable lineage health HAL

# hardware/interfaces
repopick -p 433906 #latest interfaces: fix disable_configstore

# hardware/libhardware
repopick -p 433441 #latest libhardware: Add new display types.

# hardware/lineage/interfaces
repopick -p 435570 # fastcharge: Sunset HIDL


# hardware/qcom/wlan
#repopick -p 437160 #merge caf Convert lib_driver_cmd_qcwcn for legacy to soong

# hardware/st/nfc
#repopick -p 433452 #merge Add support for text FW configs

# kernel/configs
repopick -p 433460 #latest Lower q/android-4.9 requirements

# packages/apps/Camera2
#repopick 433461 #abandone Override Aperture app

# packages/apps/Car/Settings
repopick -p 433464 #latest VolumeSettingsPreferenceController: Fix NPE when changing volumes

# packages/apps/Car/SystemUI
repopick 433465 #latest CarSystemUI: Fixes after QPR2

# packages/apps/DocumentsUI
repopick -p 433474 #latest DocumentsUI: add icons for shortcuts

# packages/apps/EmergencyInfo
repopick -p 433477 #lates EmergencyInfo: Apply insets

# packages/apps/Launcher3
repopick -p 435246 # lates Launcher3: Make taskbar start aligned in all grid sizes

# packages/apps/Settings
repopick -p 437655 #latest fixup! Fix background data clobbering other policies

# packages/apps/SettingsIntelligence
repopick -p 433482 #latest Style search bar to match new Settings UI

# packages/apps/ThemePicker
repopick -p 437122 # lates ThemePicker: default to TONAL_SPOT for invalid Styles

# packages/apps/TvSettings
repopick -p 437349 #latest TvSettings: [TvSettings] fix PendingIntent conflict in RowBuilder actions

# packages/apps/TvSystemUI
repopick 433753 # Implement USB debugging dialog

# packages/apps/WallpaperPicker2
#repopick -p 433497 #merge WallpaperPicker2: Remove unnecessary top padding in Change wallpaper button

# packages/modules/Bluetooth
repopick -p 433508 #latet BondStateMachine: Check name for validity before access

# packages/modules/Connectivity
repopick -p 436692 #latest bpf: Allow overriding kernel version

# packages/modules/Permission
repopick -p 434121 # lates SafetyCenter: Declare Advanced Protection related safety sources

# packages/modules/Wifi
#repopick 433524 # merge Wifi: Ingore miracast scan from connectivity manager

# packages/modules/adb
#repopick -p 433502 #merge Add ADB root service changes

# packages/modules/common
#repopick 433509 #merge Make adbroot_aidl_interface-ndk available for adbd

# packages/providers/DownloadProvider
#repopick -p 433527 #merge DownloadProvider: Add support for manual pause/resume

# packages/providers/TelephonyProvider
#repopick -p 433532 #abandon TelephonyProvider: add upgrade support from lineage-17.1

# packages/services/Car
repopick -p 433542 #latest car_product: Guard APN copy with LINEAGE_BUILD

# packages/services/DeviceAsWebcam
repopick -p 433544 #latest DeviceAsWebcam: jni: Make dwMaxPayloadTransferSize adjustable via property

# system/bpf
repopick -p 433560 #latest bpfloader: prog names are only valid on 4.15+

# system/chre
#repopick 433561 #merge Restore MSM CHRE daemon support

# system/core
repopick -p 437212 #latest init: add a hook before parsing system properties

# system/extras
repopick -p 433593 # bootsignature: includes dt image size for signed boot image

# system/keymaster
repopick 433595 #lates Restore ImportKeyRequest::SetKeyMaterial

# system/libhidl
repopick 433596 #latest libhidlmemory: mark as recovery_available

# system/libziparchive
#repopick 433598 #merge ziptool: restore unzip for recovery

# system/logging
repopick -p 433600 #lates liblog: Always report as debuggable when building userdebug/eng

# system/netd
repopick -p 433604 #latest VPN-covered DNS traffic may not fall through

# system/security
repopick 433605 #latest  Handle key parameter conversion for FBE_ICE tag

# system/sepolicy
repopick -p 434112 # latest Allow vsock_socket in recovery

# system/tools/mkbootimg
repopick 433617 #latest mkbootimg: add support for --dt

# system/update_engine
repopick -p 433625 #latest update_engine: Add static ota_extractor target

# system/vold
repopick -p 433641 #latest vold: Add support for ISO9660/UDF CD-ROM

# vendor/qcom/opensource/audio-hal/st-hal-ar
#repopick -p 437007 #hold until needed  st-hal-ar: Add dependency on libarpal_headers


repopick 434168 #latest lineage: Enable Material Design 3 Expressive

repopick -p 436866 #last compat: Provide libui-v34

#force qcom-caf bootctrl
repopick -p -f 436200

#qcom-caf common
repopick -p 437335

#modified by Rofikkernel
wait
